In [2]:
import numpy as np

In [5]:
arr=np.array(10)
arr

array(10)

In [6]:
arr_ffifty=np.arange(10,50)
arr_ffifty

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
arr_ffifty.shape

(40,)

In [8]:
arr_ffifty.dtype

dtype('int64')

In [10]:
import numpy as np
print(np.version)

<module 'numpy.version' from '/home/roy/anaconda3/lib/python3.8/site-packages/numpy/version.py'>


In [11]:
print(np.show_config)

<function show at 0x7f8a44511af0>


In [12]:
arr_ffifty.size

40

In [75]:
sample_arr = [True]
bool_arr = np.random.choice(sample_arr, size=10)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
arr2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
array=np.arange(60)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [17]:
arr3d=array.reshape(3,2,10)
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

In [2]:
import numpy as np
arrx=np.array([1,2,3,4,5])
arrx.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [3]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [7]:
arry_multi=arr1 * arr2
arry_multi

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [10]:
result=[]
if arry_multi%2!=0:
    result.append(i)
    print(np.array(result))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [28]:
arr=np.array([1,2,3,4,5])
arr[arr % 2 == 1]


array([1, 3, 5])

In [27]:
import numpy as np
a=np.array([1,2,3,4,5])
odd=(a%2==1)
a[odd]=-1
a

array([-1,  2, -1,  4, -1])

In [1]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[[4,8]]=12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12, 12,  9])

In [26]:
import numpy as np
x=np.ones((5,5))
print(x)
x[1:-1,1:-1]=0
x

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [1]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d




array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [5]:
arr3d= np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr3d[0][0:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
#2d array 0-9
array2d=np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
#array2d.ndim
array2d[1][1]


7

In [36]:
array2d[0:2,2]

array([3, 8])

In [37]:
value = np.random.randint(10,90,(10,10))
print(value)

[[53 82 85 60 33 60 48 27 67 41]
 [44 36 47 88 39 86 63 48 10 88]
 [55 27 23 10 77 36 39 49 15 14]
 [43 87 80 41 79 29 18 45 78 51]
 [87 80 30 11 86 31 53 79 49 11]
 [66 50 11 85 80 81 16 79 15 62]
 [60 63 83 85 16 73 50 87 46 40]
 [21 31 15 61 51 20 31 84 14 57]
 [60 69 33 75 80 12 83 59 16 80]
 [49 13 61 31 59 30 68 21 51 22]]


In [40]:
print("{0} min of the entier matrix".format(value.min()))
print("{0} max of the entier matrix".format(value.max()))

10 min of the entier matrix
88 max of the entier matrix


In [1]:
#Common Values
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [2]:
b = np.array([7,2,10,2,7,4,9,4,9,8])
b


array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [14]:
matched_value=np.where(np.intersect1d(a,b))[0]
matched_value

array([0, 1])

In [15]:
 data = np.random.randn(7, 4)
data

array([[-8.81714127e-01,  6.40119770e-01, -2.80565805e-01,
         9.19187252e-01],
       [ 5.23421860e-01,  5.85802035e-01, -2.39337639e-01,
        -2.11847021e-03],
       [ 1.55158437e+00,  7.03834135e-01,  1.41510342e-01,
         1.77254748e+00],
       [-8.36338566e-01,  4.48924987e-01, -9.84778576e-01,
        -6.06926429e-01],
       [-4.71117373e-01, -8.70000751e-02,  4.38117675e-01,
        -5.95341019e-01],
       [ 7.67912150e-02, -2.31882690e-01, -1.06216829e+00,
         1.59860039e+00],
       [-1.03514592e+00, -3.87835284e-01, -2.58998874e+00,
        -2.85763142e-01]])

In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names=='Joe'

array([False,  True, False, False, False,  True,  True])

In [20]:
print(data[names !='Joe'])
print(data[names!='Will'])

[[-0.88171413  0.64011977 -0.2805658   0.91918725]
 [ 1.55158437  0.70383414  0.14151034  1.77254748]
 [-0.83633857  0.44892499 -0.98477858 -0.60692643]
 [-0.47111737 -0.08700008  0.43811767 -0.59534102]]
[[-8.81714127e-01  6.40119770e-01 -2.80565805e-01  9.19187252e-01]
 [ 5.23421860e-01  5.85802035e-01 -2.39337639e-01 -2.11847021e-03]
 [-8.36338566e-01  4.48924987e-01 -9.84778576e-01 -6.06926429e-01]
 [ 7.67912150e-02 -2.31882690e-01 -1.06216829e+00  1.59860039e+00]
 [-1.03514592e+00 -3.87835284e-01 -2.58998874e+00 -2.85763142e-01]]


#

In [27]:
arr2d=np.random.randn(1,15)
arr2d.reshape(5,3)

array([[ 2.14768361,  1.45717235, -0.42561316],
       [ 0.1899915 , -0.78758904, -1.26338339],
       [ 0.34190934,  0.21777626, -0.33316006],
       [ 1.5708738 , -1.43366077, -0.79989358],
       [-0.09947374, -1.47317118,  0.22619946]])

In [33]:
#
arr3d= np.random.randn(1,16).reshape(2,2,4)
arr3d

array([[[ 0.14650859,  0.54854406,  0.10497616, -0.55425577],
        [-1.85310628,  0.06753039, -2.30100544,  0.45563316]],

       [[-0.54662459, -1.9863196 ,  0.86789454, -1.06667555],
        [ 1.36467854, -0.21356033, -0.34249756, -2.20564332]]])

In [34]:
arr3d= np.arange(1,17).reshape(2,2,4)
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [39]:
arrSq=np.arange(10)
arrSq
Sqrot=np.sqrt(arrSq)
np.where(Sqrot<0.5,1,Sqrot)

array([1.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names=set(names)
names

{'Bob', 'Joe', 'Will'}

In [50]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
x=np.intersect1d(a,b)
itemindex = np.where(a==x)
c=np.delete(a,itemindex)
c

array([1, 2, 3, 4])

In [59]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [60]:
newColumn = np.array([[10,10,10]])
sampleArray[1,0:]=newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

In [61]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [72]:
arrrand= np.random.randn(20)
arrrand

array([-0.77278085,  0.26079872, -0.91473248,  0.7589552 , -0.51740529,
        0.47499887,  2.90263522,  0.83497037,  0.94688553,  0.89898838,
        1.49209406, -1.33623304,  1.59461986,  0.42390154,  0.34857004,
       -1.09759831,  1.44153772, -1.20619213, -0.57024568, -1.36011632])

In [73]:
cumulative_sum=np.cumsum(arrrand,dtype=int)
cumulative_sum

array([0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 3, 2, 2, 1])